# Generated by Django 5.1.1 on 2024-09-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='type_utilisateur',
            field=models.CharField(choices=[('adminitration_menbre', "Menbre d'administration"), ('Etudiant', 'Etudiant'), ('Enseignant', 'Enseignant')], default='etudiant', max_length=255),
        ),
    ]
