# Generated by Django 5.1.1 on 2024-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='Etudes_Programme',
            field=models.CharField(choices=[('Bachelor', 'bachelor'), ('Master', 'master'), ('PhD', 'phd'), ('DEC', 'dec'), ('AEC', 'aec')], default='Bachelor', max_length=255),
        ),
    ]
