# Generated by Django 5.1.1 on 2024-09-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_etudiant_etudes_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='code_permanent',
            field=models.CharField(default='TRA05678', max_length=255),
            preserve_default=False,
        ),
    ]
