# Generated by Django 5.1.1 on 2024-09-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_etudiant_code_permanent'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='Code_proffessoral',
            field=models.CharField(default='ETRA0T5555', max_length=255),
            preserve_default=False,
        ),
    ]
