# Generated by Django 5.1.1 on 2024-09-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_enseignant_code_proffessoral'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='Semester',
            field=models.CharField(choices=[('Bachelor', 'bachelor'), ('Master', 'master'), ('PhD', 'phd'), ('DEC', 'dec'), ('AEC', 'aec')], default='hiver', max_length=255),
        ),
    ]
