# Generated by Django 5.1.1 on 2024-09-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_etudiant_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='Semester',
            field=models.CharField(choices=[('automne', 'Automn'), ('printemps', 'Printemps'), ('ete', 'Ete'), ('hiver', 'Hiver')], default='hiver', max_length=255),
        ),
    ]
