# Generated by Django 5.1.1 on 2024-09-17 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0002_alter_examen_cours'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='examens.examen'),
        ),
    ]
