# Generated by Django 5.1.1 on 2024-09-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cours_photos/'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='heure_debut',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cours',
            name='heure_fin',
            field=models.TimeField(),
        ),
    ]
