# Generated by Django 5.1.1 on 2024-09-17 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
        ('examens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='cours.cours'),
        ),
    ]
