# Generated by Django 5.1.1 on 2024-09-16 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ressource', models.CharField(choices=[('document', 'Document'), ('lien', 'Lien'), ('video', 'Vidéo')], max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='ressources/')),
                ('lien', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='cours.cours')),
            ],
        ),
    ]
